spring.application.name=nf-emissao-mvp

# Certificado Digital A1
certificado.caminho=${CERTIFICADO_CAMINHO:src/main/resources/certificados/certificado.pfx}
certificado.senha=${CERTIFICADO_SENHA:123456}

# SEFAZ
sefaz.ambiente=${SEFAZ_AMBIENTE:2}
sefaz.uf=${SEFAZ_UF:35}
sefaz.url-autorizacao=${SEFAZ_URL_AUTORIZACAO:https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao4/NFeAutorizacao4.asmx}
sefaz.url-retorno=${SEFAZ_URL_RETORNO:https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao4/NFeRetAutorizacao4.asmx}
sefaz.url-consulta=${SEFAZ_URL_CONSULTA:https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta4/NfeConsulta4.asmx}
sefaz.url-inutilizacao=${SEFAZ_URL_INUTILIZACAO:https://nfe-homologacao.svrs.rs.gov.br/ws/NfeInutilizacao4/NfeInutilizacao4.asmx}
sefaz.url-cancelamento=${SEFAZ_URL_CANCELAMENTO:https://nfe-homologacao.svrs.rs.gov.br/ws/RecepcaoEvento/RecepcaoEvento4.asmx}

# Banco de dados
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:nfedb}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:nfedb

# Armazenamento de XMLs
xml.diretorio=${XML_DIRETORIO:c:/Desenvolvimento/mvp-emissao-nf/xmls}